package com.gez.grill.entity;

import java.util.Date;

public class Caippl {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column caippl.id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column caippl.pinglsj
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	private Date pinglsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column caippl.pinglnr
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	private String pinglnr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column caippl.pingj
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	private Boolean pingj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column caippl.cant_id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	private String cantId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column caippl.caip_id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	private String caipId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column caippl.guk_id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	private String gukId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column caippl.id
	 * 
	 * @return the value of caippl.id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column caippl.id
	 * 
	 * @param id
	 *            the value for caippl.id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column caippl.pinglsj
	 * 
	 * @return the value of caippl.pinglsj
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public Date getPinglsj() {
		return pinglsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column caippl.pinglsj
	 * 
	 * @param pinglsj
	 *            the value for caippl.pinglsj
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public void setPinglsj(Date pinglsj) {
		this.pinglsj = pinglsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column caippl.pinglnr
	 * 
	 * @return the value of caippl.pinglnr
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public String getPinglnr() {
		return pinglnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column caippl.pinglnr
	 * 
	 * @param pinglnr
	 *            the value for caippl.pinglnr
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public void setPinglnr(String pinglnr) {
		this.pinglnr = pinglnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column caippl.pingj
	 * 
	 * @return the value of caippl.pingj
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public Boolean getPingj() {
		return pingj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column caippl.pingj
	 * 
	 * @param pingj
	 *            the value for caippl.pingj
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public void setPingj(Boolean pingj) {
		this.pingj = pingj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column caippl.cant_id
	 * 
	 * @return the value of caippl.cant_id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public String getCantId() {
		return cantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column caippl.cant_id
	 * 
	 * @param cantId
	 *            the value for caippl.cant_id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public void setCantId(String cantId) {
		this.cantId = cantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column caippl.caip_id
	 * 
	 * @return the value of caippl.caip_id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public String getCaipId() {
		return caipId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column caippl.caip_id
	 * 
	 * @param caipId
	 *            the value for caippl.caip_id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public void setCaipId(String caipId) {
		this.caipId = caipId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column caippl.guk_id
	 * 
	 * @return the value of caippl.guk_id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public String getGukId() {
		return gukId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column caippl.guk_id
	 * 
	 * @param gukId
	 *            the value for caippl.guk_id
	 * 
	 * @mbggenerated Tue Mar 18 18:09:37 CST 2014
	 */
	public void setGukId(String gukId) {
		this.gukId = gukId;
	}
}