package com.gez.grill.entity;

import java.sql.Date;

public class Cantsc {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cantsc.id
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cantsc.shoucsj
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	private Date shoucsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cantsc.cant_id
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	private String cantId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column cantsc.guk_id
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	private String gukId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cantsc.id
	 * 
	 * @return the value of cantsc.id
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cantsc.id
	 * 
	 * @param id
	 *            the value for cantsc.id
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cantsc.shoucsj
	 * 
	 * @return the value of cantsc.shoucsj
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	public Date getShoucsj() {
		return shoucsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cantsc.shoucsj
	 * 
	 * @param shoucsj
	 *            the value for cantsc.shoucsj
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	public void setShoucsj(Date shoucsj) {
		this.shoucsj = shoucsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cantsc.cant_id
	 * 
	 * @return the value of cantsc.cant_id
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	public String getCantId() {
		return cantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cantsc.cant_id
	 * 
	 * @param cantId
	 *            the value for cantsc.cant_id
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	public void setCantId(String cantId) {
		this.cantId = cantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column cantsc.guk_id
	 * 
	 * @return the value of cantsc.guk_id
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	public String getGukId() {
		return gukId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column cantsc.guk_id
	 * 
	 * @param gukId
	 *            the value for cantsc.guk_id
	 * 
	 * @mbggenerated Mon Mar 24 11:05:58 CST 2014
	 */
	public void setGukId(String gukId) {
		this.gukId = gukId;
	}
}