package com.gez.grill.entity;

import java.util.Date;

public class Cantpl {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column shangjpl.id
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column shangjpl.pinglsj
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	private Date pinglsj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column shangjpl.pinglnr
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	private String pinglnr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column shangjpl.pingj
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	private Boolean pingj;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column shangjpl.cant_id
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	private String cantId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column shangjpl.guk_id
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	private String gukId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shangjpl.id
	 * 
	 * @return the value of shangjpl.id
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shangjpl.id
	 * 
	 * @param id
	 *            the value for shangjpl.id
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shangjpl.pinglsj
	 * 
	 * @return the value of shangjpl.pinglsj
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public Date getPinglsj() {
		return pinglsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shangjpl.pinglsj
	 * 
	 * @param pinglsj
	 *            the value for shangjpl.pinglsj
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public void setPinglsj(Date pinglsj) {
		this.pinglsj = pinglsj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shangjpl.pinglnr
	 * 
	 * @return the value of shangjpl.pinglnr
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public String getPinglnr() {
		return pinglnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shangjpl.pinglnr
	 * 
	 * @param pinglnr
	 *            the value for shangjpl.pinglnr
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public void setPinglnr(String pinglnr) {
		this.pinglnr = pinglnr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shangjpl.pingj
	 * 
	 * @return the value of shangjpl.pingj
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public Boolean getPingj() {
		return pingj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shangjpl.pingj
	 * 
	 * @param pingj
	 *            the value for shangjpl.pingj
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public void setPingj(Boolean pingj) {
		this.pingj = pingj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shangjpl.cant_id
	 * 
	 * @return the value of shangjpl.cant_id
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public String getCantId() {
		return cantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shangjpl.cant_id
	 * 
	 * @param cantId
	 *            the value for shangjpl.cant_id
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public void setCantId(String cantId) {
		this.cantId = cantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column shangjpl.guk_id
	 * 
	 * @return the value of shangjpl.guk_id
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public String getGukId() {
		return gukId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column shangjpl.guk_id
	 * 
	 * @param gukId
	 *            the value for shangjpl.guk_id
	 * 
	 * @mbggenerated Tue Mar 18 17:17:39 CST 2014
	 */
	public void setGukId(String gukId) {
		this.gukId = gukId;
	}
}