package com.gez.grill.entity;

import java.math.BigDecimal;

public class Guk {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.id
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.weixh
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String weixh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.weixm
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String weixm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.weibm
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String weibm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.qqh
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String qqh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.zhangh
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String zhangh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.zhuangt
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String zhuangt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.mordz
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String mordz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.mordh
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String mordh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.xingm
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String xingm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.dianh1
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String dianh1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.dianh2
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String dianh2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.diz1
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String diz1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.diz2
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String diz2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.diz3
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String diz3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.diz4
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String diz4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.diz5
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String diz5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.jingd
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private BigDecimal jingd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.weid
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private BigDecimal weid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.jingd2
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private BigDecimal jingd2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.weizms
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private String weizms;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.zongdccs
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private Integer zongdccs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.zongdcfs
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private Integer zongdcfs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.zongdcje
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private BigDecimal zongdcje;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.duojf
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private Boolean duojf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.shaojf
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private Boolean shaojf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.duofl
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private Boolean duofl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.shaofl
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private Boolean shaofl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.bufc
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private Boolean bufc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.bufs
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private Boolean bufs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.bufj
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private Boolean bufj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column guk.buykz
	 * 
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	private Boolean buykz;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.id
	 * 
	 * @return the value of guk.id
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.id
	 * 
	 * @param id
	 *            the value for guk.id
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.weixh
	 * 
	 * @return the value of guk.weixh
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getWeixh() {
		return weixh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.weixh
	 * 
	 * @param weixh
	 *            the value for guk.weixh
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setWeixh(String weixh) {
		this.weixh = weixh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.weixm
	 * 
	 * @return the value of guk.weixm
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getWeixm() {
		return weixm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.weixm
	 * 
	 * @param weixm
	 *            the value for guk.weixm
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setWeixm(String weixm) {
		this.weixm = weixm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.weibm
	 * 
	 * @return the value of guk.weibm
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getWeibm() {
		return weibm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.weibm
	 * 
	 * @param weibm
	 *            the value for guk.weibm
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setWeibm(String weibm) {
		this.weibm = weibm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.qqh
	 * 
	 * @return the value of guk.qqh
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getQqh() {
		return qqh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.qqh
	 * 
	 * @param qqh
	 *            the value for guk.qqh
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setQqh(String qqh) {
		this.qqh = qqh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.zhangh
	 * 
	 * @return the value of guk.zhangh
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getZhangh() {
		return zhangh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.zhangh
	 * 
	 * @param zhangh
	 *            the value for guk.zhangh
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setZhangh(String zhangh) {
		this.zhangh = zhangh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.zhuangt
	 * 
	 * @return the value of guk.zhuangt
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getZhuangt() {
		return zhuangt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.zhuangt
	 * 
	 * @param zhuangt
	 *            the value for guk.zhuangt
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setZhuangt(String zhuangt) {
		this.zhuangt = zhuangt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.mordz
	 * 
	 * @return the value of guk.mordz
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getMordz() {
		return mordz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.mordz
	 * 
	 * @param mordz
	 *            the value for guk.mordz
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setMordz(String mordz) {
		this.mordz = mordz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.mordh
	 * 
	 * @return the value of guk.mordh
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getMordh() {
		return mordh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.mordh
	 * 
	 * @param mordh
	 *            the value for guk.mordh
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setMordh(String mordh) {
		this.mordh = mordh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.xingm
	 * 
	 * @return the value of guk.xingm
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getXingm() {
		return xingm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.xingm
	 * 
	 * @param xingm
	 *            the value for guk.xingm
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setXingm(String xingm) {
		this.xingm = xingm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.dianh1
	 * 
	 * @return the value of guk.dianh1
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getDianh1() {
		return dianh1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.dianh1
	 * 
	 * @param dianh1
	 *            the value for guk.dianh1
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setDianh1(String dianh1) {
		this.dianh1 = dianh1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.dianh2
	 * 
	 * @return the value of guk.dianh2
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getDianh2() {
		return dianh2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.dianh2
	 * 
	 * @param dianh2
	 *            the value for guk.dianh2
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setDianh2(String dianh2) {
		this.dianh2 = dianh2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.diz1
	 * 
	 * @return the value of guk.diz1
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getDiz1() {
		return diz1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.diz1
	 * 
	 * @param diz1
	 *            the value for guk.diz1
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setDiz1(String diz1) {
		this.diz1 = diz1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.diz2
	 * 
	 * @return the value of guk.diz2
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getDiz2() {
		return diz2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.diz2
	 * 
	 * @param diz2
	 *            the value for guk.diz2
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setDiz2(String diz2) {
		this.diz2 = diz2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.diz3
	 * 
	 * @return the value of guk.diz3
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getDiz3() {
		return diz3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.diz3
	 * 
	 * @param diz3
	 *            the value for guk.diz3
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setDiz3(String diz3) {
		this.diz3 = diz3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.diz4
	 * 
	 * @return the value of guk.diz4
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getDiz4() {
		return diz4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.diz4
	 * 
	 * @param diz4
	 *            the value for guk.diz4
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setDiz4(String diz4) {
		this.diz4 = diz4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.diz5
	 * 
	 * @return the value of guk.diz5
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getDiz5() {
		return diz5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.diz5
	 * 
	 * @param diz5
	 *            the value for guk.diz5
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setDiz5(String diz5) {
		this.diz5 = diz5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.jingd
	 * 
	 * @return the value of guk.jingd
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public BigDecimal getJingd() {
		return jingd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.jingd
	 * 
	 * @param jingd
	 *            the value for guk.jingd
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setJingd(BigDecimal jingd) {
		this.jingd = jingd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.weid
	 * 
	 * @return the value of guk.weid
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public BigDecimal getWeid() {
		return weid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.weid
	 * 
	 * @param weid
	 *            the value for guk.weid
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setWeid(BigDecimal weid) {
		this.weid = weid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.jingd2
	 * 
	 * @return the value of guk.jingd2
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public BigDecimal getJingd2() {
		return jingd2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.jingd2
	 * 
	 * @param jingd2
	 *            the value for guk.jingd2
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setJingd2(BigDecimal jingd2) {
		this.jingd2 = jingd2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.weizms
	 * 
	 * @return the value of guk.weizms
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public String getWeizms() {
		return weizms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.weizms
	 * 
	 * @param weizms
	 *            the value for guk.weizms
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setWeizms(String weizms) {
		this.weizms = weizms;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.zongdccs
	 * 
	 * @return the value of guk.zongdccs
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public Integer getZongdccs() {
		return zongdccs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.zongdccs
	 * 
	 * @param zongdccs
	 *            the value for guk.zongdccs
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setZongdccs(Integer zongdccs) {
		this.zongdccs = zongdccs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.zongdcfs
	 * 
	 * @return the value of guk.zongdcfs
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public Integer getZongdcfs() {
		return zongdcfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.zongdcfs
	 * 
	 * @param zongdcfs
	 *            the value for guk.zongdcfs
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setZongdcfs(Integer zongdcfs) {
		this.zongdcfs = zongdcfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.zongdcje
	 * 
	 * @return the value of guk.zongdcje
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public BigDecimal getZongdcje() {
		return zongdcje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.zongdcje
	 * 
	 * @param zongdcje
	 *            the value for guk.zongdcje
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setZongdcje(BigDecimal zongdcje) {
		this.zongdcje = zongdcje;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.duojf
	 * 
	 * @return the value of guk.duojf
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public Boolean getDuojf() {
		return duojf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.duojf
	 * 
	 * @param duojf
	 *            the value for guk.duojf
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setDuojf(Boolean duojf) {
		this.duojf = duojf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.shaojf
	 * 
	 * @return the value of guk.shaojf
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public Boolean getShaojf() {
		return shaojf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.shaojf
	 * 
	 * @param shaojf
	 *            the value for guk.shaojf
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setShaojf(Boolean shaojf) {
		this.shaojf = shaojf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.duofl
	 * 
	 * @return the value of guk.duofl
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public Boolean getDuofl() {
		return duofl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.duofl
	 * 
	 * @param duofl
	 *            the value for guk.duofl
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setDuofl(Boolean duofl) {
		this.duofl = duofl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.shaofl
	 * 
	 * @return the value of guk.shaofl
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public Boolean getShaofl() {
		return shaofl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.shaofl
	 * 
	 * @param shaofl
	 *            the value for guk.shaofl
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setShaofl(Boolean shaofl) {
		this.shaofl = shaofl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.bufc
	 * 
	 * @return the value of guk.bufc
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public Boolean getBufc() {
		return bufc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.bufc
	 * 
	 * @param bufc
	 *            the value for guk.bufc
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setBufc(Boolean bufc) {
		this.bufc = bufc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.bufs
	 * 
	 * @return the value of guk.bufs
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public Boolean getBufs() {
		return bufs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.bufs
	 * 
	 * @param bufs
	 *            the value for guk.bufs
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setBufs(Boolean bufs) {
		this.bufs = bufs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.bufj
	 * 
	 * @return the value of guk.bufj
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public Boolean getBufj() {
		return bufj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.bufj
	 * 
	 * @param bufj
	 *            the value for guk.bufj
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setBufj(Boolean bufj) {
		this.bufj = bufj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column guk.buykz
	 * 
	 * @return the value of guk.buykz
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public Boolean getBuykz() {
		return buykz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column guk.buykz
	 * 
	 * @param buykz
	 *            the value for guk.buykz
	 * @mbggenerated Mon Mar 17 12:03:08 CST 2014
	 */
	public void setBuykz(Boolean buykz) {
		this.buykz = buykz;
	}
}